-- BUỔI 06: BẢNG TỔNG HỢP DỮ LIỆU (PIVOT TABLE) & CHỦ ĐỀ XẾP HẠNG (RANKING TOPIC)

-- 1. PHƯƠNG PHÁP PIVOT TABLE
-- GỒM 03 PHẦN:
---> PHẦN 1: CHỌN CÁC CỘT CẦN HIỂN THỊ 
---> PHẦN 2: DATA CẦN PIVOT
---> PHẦN 3: CHUYỂN ĐỔI DÒNG THÀNH CỘT
-- CỤ THỂ CÚ PHÁP NHƯ SAU:

SELECT ---> PHẦN 1: CHỌN CÁC CỘT CẦN HIỂN THỊ 
<NON-PIVOTED COLUMN>, ---> CỘT KHÔNG XOAY CHUYỂN
[FIRST PIVOTED COLUMN] AS <COLUMN NAME>, ---> GIÁ TRỊ ĐẦU TIÊN ĐƯỢC XOAY CHUYỂN THÀNH CỘT
[SECOND PIVOTED COLUMN] AS <COLUMN NAME>, ---> GIÁ TRỊ THỨ HAI ĐƯỢC XOAY CHUYỂN THÀNH CỘT
[LAST PIVOTED COLUMN] AS <COLUMN NAME> ---> GIÁ TRỊ CUỐI ĐƯỢC XOAY CHUYỂN THÀNH CỘT
FROM   ---> PHẦN 2: DATA CẦN PIVOT
(<SELECT QUERY THAT PRODUCES THE DATA>) AS PIVOTDATA
PIVOT  ---> PHẦN 3: CHUYỂN ĐỔI DÒNG THÀNH CỘT
( <HÀM TỔNG HỢP>
FOR [<CỘT CHỨA CÁC GIÁ TRỊ SẼ TRỞ THÀNH TIÊU ĐỀ CỘT>]
IN ( [FIRST PIVOTED COLUMN], [SECOND PIVOTED COLUMN], ... [LAST PIVOTED COLUMN]) ) AS PIVOTTABLE

-- VÍ DỤ:
SELECT
CUSTOMER_NAME,
"OFFICE SUPPLIES",
"FURNITURE",
"TECHNOLOGY"
FROM
(
SELECT CUSTOMER_NAME,
PRODUCT_CATEGORY,
PROFIT
FROM ORDERS
) AS PIVOTDATA
PIVOT
(
SUM(PROFIT)
FOR PRODUCT_CATEGORY IN ( "OFFICE SUPPLIES", "FURNITURE","TECHNOLOGY")
) AS PIVOTTABLE

-- THỰC HÀNH: BẰNG CÁCH PIVOT TÍNH TỔNG LN CỦA MỖI TỈNH THEO MỨC ĐỘ ƯU TIÊN
SELECT
PROVINCE,
"HIGH",
"LOW",
"MEDIUM",
"CRITICAL",
"NOT SPECIFIED"
FROM
(
   SELECT ORDER_PRIORITY, PROVINCE, PROFIT
   FROM ORDERS
) AS PIVOTDATA
PIVOT
(
  SUM(PROFIT)
  FOR ORDER_PRIORITY IN ("HIGH", "LOW", "MEDIUM", "CRITICAL", "NOT SPECIFIED")
) AS PIVOT_TABLE

-- THỰC HÀNH: TỔNG HỢP SỐ LƯỢNG ĐƠN HÀNG CỦA MỖI TỈNH THEO MỖI HÌNH THỨC SHIPPING (SHIPPING_MODE)
-- SỬ DỤNG PIVOTTABLE ĐỂ TỔNG HỢP CÁC GIÁ TRỊ CỦA SHIPPING_MODE THÀNH CỘT
-- TA CÓ:
SELECT DISTINCT SHIPPING_MODE FROM ORDERS
--> CÚ PHÁP:
SELECT
PROVINCE,
"DELIVERY TRUCK",
"EXPRESS AIR",
"REGULAR AIR"
FROM
(
SELECT SHIPPING_MODE, ORDER_ID, PROVINCE
FROM ORDERS
) AS PIVOT_DATA
PIVOT
(
COUNT(ORDER_ID)
FOR SHIPPING_MODE IN ( "DELIVERY TRUCK", "EXPRESS AIR", "REGULAR AIR")
) AS PIVOT_TABLE

-- 2. CHỦ ĐỀ XẾP HẠNG (RANKING TOPIC):
-- SỬ DỤNG HÀM ROW_NUMBER (), RANK() VÀ DENSE_RANK()
---? PHÂN BIỆT ROW_NUMBER, RANK VÀ DENSE_RANK:
---> ĐẦU TIÊN, BẠN NHÌN VÍ DỤ SAU:

SELECT CUSTOMER_NAME, ORDER_ID, ORDER_DATE,
ROW_NUMBER() OVER(ORDER BY ORDER_DATE ASC) AS [ROW_NUMBER],
RANK() OVER(ORDER BY ORDER_DATE ASC) AS [RANK],
DENSE_RANK() OVER(ORDER BY ORDER_DATE ASC) AS [DENSE_RANK]
FROM ORDERS
WHERE CUSTOMER_NAME = 'TAMARA CHAND';

-- CHẠY KẾT QUẢ RA NHẬN THẤY:
-- CẢ 3 HÀM ĐỀU ORDER BY ORDER_DATE
-- HÀM ROW_NUMBER DÙNG ĐỂ XẾP HẠNG KẾT QUẢ MỘT CÁCH TUẦN TỰ BẮT ĐẦU TỪ 1 VÀ KHÔNG QUAN TÂM ĐẾN CÁC GIÁ TRỊ GIỐNG NHAU.
-- TẠI DÒNG THỨ 2 VÀ DÒNG 3, GIÁ TRỊ ORDER_DATE ĐỀU GIỐNG NHAU. RANK VÀ DENSE_RANK ĐỀU TRẢ VỀ GIÁ TRỊ LÀ 2.
-- TẠI DÒNG THỨ 4, HÀM RANK TRỰC TIẾP BẮT KỊP GIÁ TRỊ CỦA ROW_NUMBER BẰNG CÁCH BỎ ĐI GIÁ TRỊ 3. CÒN DENSE_RANK THÌ TRẢ VỀ GIÁ TRỊ TIẾP THEO DỰA TRÊN DÒNG TRƯỚC ĐÓ. TƯƠNG TỰ VỚI CÁC DÒNG DƯỚI

-- NHƯ VẬY CỤ THỂ TỪNG HÀM:

-- A. HÀM ROW_NUMBER() : THƯỜNG TÌM TOP N CAO NHẤT/ THẤP NHẤT THEO 1 HAY NHIỀU TIÊU CHÍ:
-- CÚ PHÁP:
ROW_NUMBER ( ) OVER ( [ PARTITION BY COLUMNS] ORDER BY COLUMN ASC|DESC ) AS ROW_NUM
-- TÍNH CHẤT: XẾP HẠNG THEO THỨ TỰ TĂNG DẦN KHÔNG QUAN TÂM ĐẾN CÁC GIÁ TRỊ GIỐNG NHAU
-- THỰC HÀNH:
-- LẤY DANH SÁCH CÁC ĐƠN HÀNG (ORDER_ID) DỰA VÀO NGÀY GIAO HÀNG (SHIPPING_DATE) VÀ CHO BIẾT ĐƠN HÀNG ĐÓ LÀ ĐƠN HÀNG THỨ MẤY ĐƯỢC SHIP ĐI.
-- KẾT QUẢ HIỂN THỊ CẦN CÁC CỘT: ORDER_ID, ORDER_DATE, ROW_NUM (THỨ TỰ SHIP HÀNG)
SELECT ORDER_ID, SHIPPING_DATE,
ROW_NUMBER ( ) OVER ( ORDER BY SHIPPING_DATE ASC ) 
AS ROW_NUM
FROM ORDERS;

-- B. HÀM DENSE_RANK() : THƯỜNG DÙNG ĐỂ XẾP HẠNG (DOANH SỐ CỦA MÌNH ĐƯNG THỨ MẤY KHI SO VỚI DOANH SỐ CỦA TẤT CẢ MN)
-- CÚ PHÁP: 
DENSE_RANK ( ) OVER ( [ PARTITION BY COLUMNS ] ORDER BY COLUMNS ASC|DESC ) AS DENSE_RANK_COL
-- TÍNH CHẤT: XẾP HẠNG THEO THỨ TỰ TĂNG DẦN, CÁC GIÁ TRỊ GIỐNG NHAU CÓ THỨ HẠNG BẰNG NHAU.
-- THỰC HÀNH:
-- XẾP HẠNG GIÁ TRỊ LỢI NHUẬN TĂNG DẦN CỦA MỖI ĐƠN HÀNG Ở MỖI TỈNH
-- KẾT QUẢ HIỂN THỊ GỒM CÁC CỘT: PROVINCE, ORDER_ID, PROFIT, DENSE_RANK_COL (CỘT XẾP HẠNG)
-- VÍ DỤ:
SELECT
PROVINCE, ORDER_ID, PROFIT,
DENSE_RANK() OVER ( PARTITION BY PROVINCE ORDER BY PROFIT ASC ) 
AS DENSE_RANK_COL
FROM ORDERS;

-- C. HÀM RANK() : THƯỜNG DÙNG ĐỂ TÌM VỊ TRÍ (VÍ DỤ DOANH SỐ KÉM SO VỚI BN NGƯỜI, BN NGƯỜI CÓ DOANH SỐ CAO HƠN MÌNH)
-- CÚ PHÁP:
RANK ( ) OVER ( [ PARTITION BY COLUMNS ] ORDER BY COLUMNS ASC|DESC)
-- TÍNH CHẤT: XẾP HẠNG THEO THỨ BẬC TĂNG DẦN, CÁC GIÁ TRỊ GIỐNG NHAU CÓ CÙNG THỨ BẬC, 
-- GIÁ TRỊ TIẾP THEO CÓ THỂ NHẢY N BẬC NẾU THỨ BẬC TRƯỚC CÓ N GIÁ TRỊ GIỐNG NHAU
-- THỰC HÀNH:
-- XẾP HẠNG THỨ BẬC GIÁ TRỊ LỢI NHUẬN TĂNG DẦN CỦA MỖI ĐƠN HÀNG Ở MỖI TỈNH
-- KẾT QUẢ HIỂN THỊ GỒM CÁC CỘT: PROVINCE, ORDER_ID, PROFIT, RANK_COL (CỘT XẾP HẠNG)
SELECT
PROVINCE, ORDER_ID, PROFIT,
RANK() OVER ( PARTITION BY PROVINCE ORDER BY PROFIT ASC )
AS RANK_COL
FROM ORDERS;

-- MỘT SỐ ĐẦU BÀI TIÊU BIỂU:
--- 1. LẤY DANH SÁCH TOP 03 SẢN PHẨM CÓ DOANH SỐ CAO NHẤT MỖI THÁNG CỦA NĂM 2012:
--- 2. LẤY DS TOP 5 SẢN PHẨM CÓ TỔNG LỢI NHUẬN CAO NHẤT CỦA MỖI TỈNH:
---> CÁCH 1:
WITH A AS
(SELECT 
PROVINCE,
PRODUCT_NAME,
SUM(PROFIT) AS TOTAL_PROFIT,
ROW_NUMBER() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
FROM ORDERS
GROUP BY PROVINCE, PRODUCT_NAME)
SELECT * FROM A WHERE ROW_NUM <=5;

---> CÁCH 2:
SELECT * FROM
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME) AS A
WHERE ROW_NUM <=5;

-- CHÚ Ý: PARTITION BY XÁC ĐỊNH VÒNG LẶP THEO CÁI GÌ, CÁI MÀ MÌNH PHẢI RANK (CAO NHẤT, THẤP NHẤT CỦA "CÁI GÌ")
-- THÌ SAU PARTITION BY SẼ LÀ CÁI ĐÓ
-- NẾU MỖI TỈNH, MỖI MỨC ĐỘ ƯU TIÊN CHỌN RA TOP N CAO NHẤT, THẤP NHẤT => PARTITION BY CẢ 2 CÁI

--- 3. LẤY DS TOP 5 SẢN PHẨM CÓ TỔNG LỢI NHUẬN CAO NHẤT CỦA MỖI TỈNH Ở MỖI MỨC ĐỘ ƯU TIÊN:
---> CÁCH 1:
WITH A AS
  (SELECT 
  PROVINCE,
  ORDER_PRIORITY,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE, ORDER_PRIORITY ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME, ORDER_PRIORITY)
SELECT * FROM A WHERE ROW_NUM <=5;

---> CÁCH 2:
SELECT * FROM
  (SELECT 
  PROVINCE,
  ORDER_PRIORITY,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE, ORDER_PRIORITY ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME, ORDER_PRIORITY) AS A
WHERE ROW_NUM <=5;

--- 4. LẤY DANH SÁCH TOP 3 KH MANG LẠI LN CAO NHẤT CỦA MỖI MỨC ĐỘ ƯU TIÊN
---> CÁCH 1:
WITH A AS
  (SELECT 
  CUSTOMER_NAME,
  ORDER_PRIORITY,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY ORDER_PRIORITY ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY CUSTOMER_NAME, ORDER_PRIORITY)
SELECT * FROM A WHERE ROW_NUM <=3;

---> CÁCH 2:
SELECT * FROM 
  (SELECT 
  CUSTOMER_NAME,
  ORDER_PRIORITY,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY ORDER_PRIORITY ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY CUSTOMER_NAME, ORDER_PRIORITY) AS A
WHERE ROW_NUM <=3;

--- 5. ---LẤY DANH SÁCH TOP 3 SẢN PHẨM CÓ TỔNG SỐ LƯỢNG ĐƠN HÀNG THẤP NHẤT 
       -- THEO MỖI LOẠI SẢN PHẨM (PRODUCT_CATEGORY) Ở MỖI TỈNH
---> CÁCH 1:
WITH A AS
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  PRODUCT_CATEGORY,
  COUNT (DISTINCT ORDER_ID) AS TOTAL_ORDERS,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE, PRODUCT_CATEGORY ORDER BY COUNT(DISTINCT ORDER_ID) ASC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_CATEGORY, PRODUCT_NAME)
SELECT * FROM A WHERE ROW_NUM <=3;

---> CÁCH 2:
SELECT * FROM
(SELECT 
  PROVINCE,
  PRODUCT_NAME,
  PRODUCT_CATEGORY,
  COUNT (DISTINCT ORDER_ID) AS TOTAL_ORDERS,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE, PRODUCT_CATEGORY ORDER BY COUNT(DISTINCT ORDER_ID) ASC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_CATEGORY, PRODUCT_NAME) AS A
WHERE ROW_NUM <=3;

--- 6. LẤY DS TOP 3 KHÁCH HÀNG CÓ TỔNG ĐƠN HÀNG CAO NHẤT CỦA MỖI NĂM
---> CÁCH 1:
WITH A AS
  (SELECT 
  YEAR(ORDER_DATE) AS YEAR,
  CUSTOMER_NAME,
  COUNT (DISTINCT ORDER_ID) AS TOTAL_ORDERS,
  ROW_NUMBER() OVER(PARTITION BY YEAR(ORDER_DATE) ORDER BY COUNT(DISTINCT ORDER_ID) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY CUSTOMER_NAME, YEAR(ORDER_DATE))
SELECT * FROM A WHERE ROW_NUM <=3;

---> CÁCH 3:
SELECT * FROM
  (SELECT 
  YEAR(ORDER_DATE) AS YEAR,
  CUSTOMER_NAME,
  COUNT (DISTINCT ORDER_ID) AS TOTAL_ORDERS,
  ROW_NUMBER() OVER(PARTITION BY YEAR(ORDER_DATE) ORDER BY COUNT(DISTINCT ORDER_ID) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY CUSTOMER_NAME, YEAR(ORDER_DATE)) AS A
WHERE ROW_NUM <=3;

--- 7. LẤY SẢN PHẨM CÓ TỔNG LỢI NHUẬN VỊ TRÍ CAO THỨ 7 THEO MỖI TỈNH
---> CÁCH 1:
WITH A AS
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME)
SELECT * FROM A WHERE RANK_NUM=7;
---> CÁCH 1:
SELECT * FROM 
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME) AS A
WHERE RANK_NUM=7;

--- 8. LẤY LOẠI SẢN PHẨM CÓ TỔNG ĐƠN HÀNG CÓ HẠNG THẤP THỨ 3 TỪ DƯỚI LÊN THEO MỖI MỨC ĐỘ ƯU TIÊN.
---> CÁCH 1:
WITH A AS
  (SELECT 
  ORDER_PRIORITY,
  PRODUCT_CATEGORY,
  COUNT(DISTINCT ORDER_ID) AS TOTAL_PROFIT,
  DENSE_RANK() OVER(PARTITION BY ORDER_PRIORITY ORDER BY COUNT(DISTINCT ORDER_ID) ASC) AS DENSE_RANK_NUM
  FROM ORDERS
  GROUP BY ORDER_PRIORITY, PRODUCT_CATEGORY)
SELECT * FROM A WHERE DENSE_RANK_NUM=3;

---> CÁCH 2:
SELECT * FROM
  (SELECT 
  ORDER_PRIORITY,
  PRODUCT_CATEGORY,
  COUNT(DISTINCT ORDER_ID) AS TOTAL_PROFIT,
  DENSE_RANK() OVER(PARTITION BY ORDER_PRIORITY ORDER BY COUNT(DISTINCT ORDER_ID) ASC) AS DENSE_RANK_NUM
  FROM ORDERS
  GROUP BY ORDER_PRIORITY, PRODUCT_CATEGORY) AS A
WHERE DENSE_RANK_NUM = 3;

-- THỰC HÀNH TRONG SLIDE:
-- BÀI 1: LẤY RA DANH SÁCH CÁC ĐƠN HÀNG (ORDER_ID) CÓ LỢI NHUẬN (PROFIT) XẾP HẠNG CAO NHẤT (XẾP HẠNG THỨ NHẤT) CỦA MỖI TỈNH
-- GỢI Ý: SỬ DỤNG DENSE_RANK() ĐỂ XẾP HẠNG
---> CÁCH 1:
SELECT * FROM
(SELECT
PROVINCE, ORDER_ID, PROFIT,
DENSE_RANK() OVER ( PARTITION BY PROVINCE ORDER BY PROFIT DESC ) 
AS DENSE_RANK_COL
FROM ORDERS) AS A
WHERE DENSE_RANK_COL = 1;

---> CÁCH 2:
WITH A AS
(SELECT
PROVINCE, ORDER_ID, PROFIT,
DENSE_RANK() OVER ( PARTITION BY PROVINCE ORDER BY PROFIT DESC ) 
AS DENSE_RANK_COL
FROM ORDERS
GROUP BY PROVINCE, ORDER_ID, PROFIT)
SELECT * FROM A 
WHERE DENSE_RANK_COL = 1;

-- BÀI 2: LẤY DANH SÁCH TOP 3 LOẠI SẢN PHẨM CÓ TỔNG LỢI NHUẬN CAO NHẤT Ở MỖI TỈNH
-- GỢI Ý: SỬ DỤNG ROW_NUMBER() ĐỂ XẾP HẠNG
---> CÁCH 1:
WITH A AS
(SELECT 
PROVINCE,
PRODUCT_CATEGORY,
SUM(PROFIT) AS TOTAL_PROFIT,
ROW_NUMBER() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
FROM ORDERS
GROUP BY PROVINCE, PRODUCT_CATEGORY)
SELECT * FROM A WHERE ROW_NUM <=3;
---> CÁCH 2:
SELECT * FROM
  (SELECT 
  PROVINCE,
  PRODUCT_CATEGORY,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_CATEGORY) AS A
WHERE ROW_NUM <=3;

-- BÀI TẬP VỀ NHÀ:
-- BÀI 1: SỬ DỤNG PHƯƠNG PHÁP PIVOTTABLE
-- HÃY TÍNH TỔNG GIÁ TRỊ (TOTAL_VALUE) CỦA MỖI TỈNH THEO TỪNG LOẠISẢN PHẨM (PRODUCT_CATEGORY). 

SELECT
PROVINCE,
"OFFICE SUPPLIES",
"FURNITURE",
"TECHNOLOGY"
FROM
(
SELECT PROVINCE, VALUE, PRODUCT_CATEGORY
FROM ORDERS
) AS PIVOT_DATA
PIVOT
(
SUM(VALUE)
FOR PRODUCT_CATEGORY IN ( "OFFICE SUPPLIES", "FURNITURE", "TECHNOLOGY" )
) AS PIVOT_TABLE;

-- BÀI 2: SỬ DỤNG ROW_NUMBER () 
-- LẤY DANH SÁCH TOP 3 SẢN PHẨM (PRODUCT_NAME) CÓ TỔNG LỢI NHUẬN (TOTAL_PROFIT) NHỎ NHẤT CỦA MỖI LOẠI SẢN PHẨM (PRODUCT_CATEGORY)

---> CÁCH 1:
WITH A AS
  (SELECT
  PRODUCT_CATEGORY,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PRODUCT_CATEGORY ORDER BY SUM(PROFIT) ASC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_CATEGORY, PRODUCT_NAME)
SELECT * FROM A WHERE ROW_NUM <=3;

---> CÁCH 2:
SELECT * FROM
  (SELECT
  PRODUCT_CATEGORY,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  ROW_NUMBER() OVER(PARTITION BY PRODUCT_CATEGORY ORDER BY SUM(PROFIT) ASC) AS ROW_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_CATEGORY, PRODUCT_NAME) AS A
WHERE ROW_NUM <=3;

-- BÀI 3: SỬ DỤNG DENSE_RANK ()
-- XÁC ĐỊNH NHỮNG SẢN PHẨM (PRODUCT_NAME) CÓ TỔNG LỢI NHUẬN XẾP HẠNG 3 (TỪ TRÊN XUỐNG) CỦA MỖI TỈNH

---> CÁCH 1:
WITH A AS
  (SELECT 
  PROVINCE, 
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  DENSE_RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS DENSE_RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME)
SELECT * FROM A WHERE DENSE_RANK_NUM=3;

---> CÁCH 2:
SELECT * FROM
  (SELECT 
  PROVINCE, 
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  DENSE_RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) DESC) AS DENSE_RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME) AS A
WHERE DENSE_RANK_NUM=3;

-- BÀI 4: SỬ DỤNG RANK ()
-- XÁC ĐỊNH NHỮNG SẢN PHẨM (PRODUCT_NAME) CÓ TỔNG LỢI NHUẬN XẾP VÍ TRÍ THỨ 3 (TỪ DƯỚI LÊN) CỦA MỖI TỈNH

---> CÁCH 1:
WITH A AS
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) ASC) AS RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME)
SELECT * FROM A WHERE RANK_NUM=3;
---> CÁCH 1:
SELECT * FROM 
  (SELECT 
  PROVINCE,
  PRODUCT_NAME,
  SUM(PROFIT) AS TOTAL_PROFIT,
  RANK() OVER(PARTITION BY PROVINCE ORDER BY SUM(PROFIT) ASC) AS RANK_NUM
  FROM ORDERS
  GROUP BY PROVINCE, PRODUCT_NAME) AS A
WHERE RANK_NUM=3;
